# Shell variables
# Generated by 'wal'
wallpaper="/home/fhasl/Pictures/Wallpapers/chromatic_light_1.jpg"

# Special
background='#253337'
foreground='#c8cccd'
cursor='#c8cccd'

# Colors
color0='#253337'
color1='#3F858E'
color2='#498A92'
color3='#6F9499'
color4='#6B9FA4'
color5='#989A9A'
color6='#94A7AA'
color7='#c8cccd'
color8='#6b7c82'
color9='#3F858E'
color10='#498A92'
color11='#6F9499'
color12='#6B9FA4'
color13='#989A9A'
color14='#94A7AA'
color15='#c8cccd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
