--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/fhasl/Pictures/Wallpapers/chromatic_light_1.jpg"

-- Special
background="#253337"
foreground="#c8cccd"
cursor="#c8cccd"

-- Colors
color0="#253337"
color1="#3F858E"
color2="#498A92"
color3="#6F9499"
color4="#6B9FA4"
color5="#989A9A"
color6="#94A7AA"
color7="#c8cccd"
color8="#6b7c82"
color9="#3F858E"
color10="#498A92"
color11="#6F9499"
color12="#6B9FA4"
color13="#989A9A"
color14="#94A7AA"
color15="#c8cccd"
